### ISSUE TITLE
support UDM-Pro 1.10.0-13.3677

### ISSUE THREAD

**Issue by theeddie** [tusc/wireguard-kmod#10]
loading wireguard...
insmod: can't insert '/mnt/data/wireguard/wireguard-4.19.152-al-linux-v10.2.0-v1.10.0-13.3677-0ebe4e7.ko': No such file or directory
insmod: can't insert '/mnt/data/wireguard/iptable_raw-4.19.152-al-linux-v10.2.0-v1.10.0-13.3677-0ebe4e7.ko': No such file or directory

**Comment by peacey** [comment]
Hi @theeddie. There is already an issue for this opened in issue #7. There is a download link posted there to the .ko modules for 1.10.0-13. You can try them out and see if they work.
