### ISSUE TITLE
Using UDM as a wireguard client

### ISSUE THREAD

**Issue by ephemer** [tusc/wireguard-kmod#14]
Hi, thanks a lot for your work on this! It looks like you’ve done some great stuff here and I’m looking forward to trying it out soon.

I have a question rather than an issue (and it’s a noob question, sorry): is it possible to use this package to set the UDM/Pro up as a Wireguard client and route all UDM-client traffic destined for the foreign IP range via the VPN?

My use case is a UDM Pro in the office and UDM at home which would ideally be permanently connected via WG to the office (removing the need to set up my home devices to make individual wg connections).

If yes, is this trivial and it “just works” or do I need to get deeper into routing tables and firewall rules manually? I’m assuming it’s the latter, but unsure how to set up routing manually - would the UniFi UI suffice for this?

**Comment by peacey** [comment]
Hi @ephemer,

Yes you can do that. You can run WG on one UDM as a server, then use the other UDM as a WG client connected to the first UDM. You can specify in the WG config what destination subnets you want to route through this tunnel using AllowedIPs config variable on the client. 

But why do you need WG for this? If you're just connecting two UDMs together, why can't you just use the built-in site-to-site?

**Comment by ephemer** [comment]
Hi @peacey, thanks for your reply. The problem with the builtin site-to-site is that it requires static IPs on both sides of the tunnel – we only have a static IP in the office, so that setup is not possible for us. Maybe we will have the same issue with WG, I guess I'll find out. I also assume WG will provide us better link performance and maybe even better security too.

**Comment by peacey** [comment]
Oh I see. You are right, WireGuard only needs the server to have a static IP, or a domain connected that updates the dynamic IP when it changes. The client's IP is not used anywhere so is irrelevant. 

As for performance, WG has the same performance as the built-in L2TP site-to-site (~ 1 Gbps).
