### ISSUE TITLE
insmod: can't insert ....

### ISSUE THREAD

**Issue by EisernUnion** [tusc/wireguard-kmod#19]

**Comment by EisernUnion** [comment]
Hi,
my output when running the setup 
... 'wireguard-4.19.152-al-linux-v10.2.0-v1.10.0.3686-a2edd0c.ko': No such file or directory 
... 'iptable_raw-4.19.152-al-linux-v10.2.0-v1.10.0.3686-a2edd0c.ko': No such file or directory

**Comment by peacey** [comment]
Hi @EisernUnion, did you update to the latest version? The latest version already includes this module.

**Comment by chrisstaite** [comment]
I think my fix for #20 fixes this also.
