### ISSUE TITLE
insmod: can't insert -> UniFi OS Version 1.11.0-14

### ISSUE THREAD

**Issue by giszmo2002** [tusc/wireguard-kmod#20]
insmod: can't insert '/mnt/data/wireguard/wireguard-4.19.152-al-linux-v10.2.0-v1.11.0-14.3859-c147cc8.ko': No such file or directory
insmod: can't insert '/mnt/data/wireguard/iptable_raw-4.19.152-al-linux-v10.2.0-v1.11.0-14.3859-c147cc8.ko': No such file or directory
insmod: can't insert '/mnt/data/wireguard/ip6table_raw-4.19.152-al-linux-v10.2.0-v1.11.0-14.3859-c147cc8.ko': No such file or directory

**Comment by chrisstaite** [comment]
Should now be fixed.
