### ISSUE TITLE
UDMP Install Issue

### ISSUE THREAD

**Issue by jlauzer11** [tusc/wireguard-kmod#23]
I have a couple of new UDM-P's that I am trying to install on.  I must be doing something wrong because my UDMPSE worked.

I downloaded the .tar.gz file.  I ran the extraction... But it put it into /mnt/data/wireguard-kmod-8-10-21 folder.  I navigated over there and went into /src/wireguard and found the setup.  When I run it, I get permission denied.  When I ran sudo in front of it it states command not found.  Below is all the steps.  The devices is running Unifi OS 1.10.0.

`      Welcome to UniFi Dream Machine!
# unifi-os shell
root@ubnt:~# curl -LJo wireguard-kmod.tar.Z https://github.com/tusc/wireguard-kmod/archive/refs/tags/v8-10-21.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   139  100   139    0     0    616      0 --:--:-- --:--:-- --:--:--   617
100  320k    0  320k    0     0   452k      0 --:--:-- --:--:-- --:--:-- 7879k
root@ubnt:~# tar -C /mnt/data -xvzf wireguard-kmod.tar.Z
wireguard-kmod-8-10-21/
wireguard-kmod-8-10-21/.gitattributes
wireguard-kmod-8-10-21/README.building.md
wireguard-kmod-8-10-21/README.md
wireguard-kmod-8-10-21/images/
wireguard-kmod-8-10-21/images/PortGroup.png
wireguard-kmod-8-10-21/images/WireGuardRule.png
wireguard-kmod-8-10-21/images/qrencode.png
wireguard-kmod-8-10-21/releases/
wireguard-kmod-8-10-21/releases/README.md
wireguard-kmod-8-10-21/src/
wireguard-kmod-8-10-21/src/build-wireguard.sh
wireguard-kmod-8-10-21/src/linux-1.10.0-12.tar.gz
wireguard-kmod-8-10-21/src/linux-1.10.0-8.tar.gz
wireguard-kmod-8-10-21/src/linux-1.9.0-10.tar.gz
wireguard-kmod-8-10-21/src/packages/
wireguard-kmod-8-10-21/src/packages/openresolv/
wireguard-kmod-8-10-21/src/packages/openresolv/Config.in
wireguard-kmod-8-10-21/src/packages/openresolv/openresolv.hash
wireguard-kmod-8-10-21/src/packages/openresolv/openresolv.mk
wireguard-kmod-8-10-21/src/packages/wireguard-linux-compat/
wireguard-kmod-8-10-21/src/packages/wireguard-linux-compat/Config.in
wireguard-kmod-8-10-21/src/packages/wireguard-linux-compat/wireguard-linux-compat.hash
wireguard-kmod-8-10-21/src/packages/wireguard-linux-compat/wireguard-linux-compat.mk
wireguard-kmod-8-10-21/src/packages/wireguard-tools/
wireguard-kmod-8-10-21/src/packages/wireguard-tools/Config.in
wireguard-kmod-8-10-21/src/packages/wireguard-tools/wireguard-tools.hash
wireguard-kmod-8-10-21/src/packages/wireguard-tools/wireguard-tools.mk
wireguard-kmod-8-10-21/src/patches/
wireguard-kmod-8-10-21/src/patches/0001-bison-glibc-change-work-around.patch
wireguard-kmod-8-10-21/src/patches/0001-dtc-extern-yylloc.patch
wireguard-kmod-8-10-21/src/patches/0001-m4-glibc-change-work-around.patch
wireguard-kmod-8-10-21/src/patches/944-mpc-relative-literal-loads-logic-in-aarch64_classify_symbol.patch
wireguard-kmod-8-10-21/src/patches/add-kernel-4-19.patch
wireguard-kmod-8-10-21/src/patches/openresolv-package.patch
wireguard-kmod-8-10-21/src/patches/wireguard-packages.patch
wireguard-kmod-8-10-21/src/udm-1.10.0-12/
wireguard-kmod-8-10-21/src/udm-1.10.0-12/UDM-config.txt
wireguard-kmod-8-10-21/src/udm-1.10.0-12/buildroot-config.txt
wireguard-kmod-8-10-21/src/udm-1.10.0-12/prefix
wireguard-kmod-8-10-21/src/udm-1.10.0-12/versions.txt
wireguard-kmod-8-10-21/src/udm-1.10.0-8/
wireguard-kmod-8-10-21/src/udm-1.10.0-8/UDM-config.txt
wireguard-kmod-8-10-21/src/udm-1.10.0-8/buildroot-config.txt
wireguard-kmod-8-10-21/src/udm-1.10.0-8/prefix
wireguard-kmod-8-10-21/src/udm-1.10.0-8/versions.txt
wireguard-kmod-8-10-21/src/udm-1.9.0-10/
wireguard-kmod-8-10-21/src/udm-1.9.0-10/UDM-config.txt
wireguard-kmod-8-10-21/src/udm-1.9.0-10/buildroot-config.txt
wireguard-kmod-8-10-21/src/udm-1.9.0-10/linux-patches/
wireguard-kmod-8-10-21/src/udm-1.9.0-10/linux-patches/linux-0001-dtc-lexer.patch
wireguard-kmod-8-10-21/src/udm-1.9.0-10/prefix
wireguard-kmod-8-10-21/src/udm-1.9.0-10/versions.txt
wireguard-kmod-8-10-21/src/udm-se-1.10.0-12/
wireguard-kmod-8-10-21/src/udm-se-1.10.0-12/UDM-config.txt
wireguard-kmod-8-10-21/src/udm-se-1.10.0-12/buildroot-config.txt
wireguard-kmod-8-10-21/src/udm-se-1.10.0-12/linux-patches/
wireguard-kmod-8-10-21/src/udm-se-1.10.0-12/linux-patches/linux-0001-localversion.patch
wireguard-kmod-8-10-21/src/udm-se-1.10.0-12/prefix
wireguard-kmod-8-10-21/src/udm-se-1.10.0-12/versions.txt
wireguard-kmod-8-10-21/src/wireguard/
wireguard-kmod-8-10-21/src/wireguard/etc/
wireguard-kmod-8-10-21/src/wireguard/etc/wireguard/
wireguard-kmod-8-10-21/src/wireguard/etc/wireguard/wg0.conf.sample
wireguard-kmod-8-10-21/src/wireguard/setup_wireguard.sh
wireguard-kmod-8-10-21/src/wireguard/usr/
wireguard-kmod-8-10-21/src/wireguard/usr/bin/
wireguard-kmod-8-10-21/src/wireguard/usr/bin/wg-quick
root@ubnt:~# cd /mnt/data
root@ubnt:/mnt/data# ls
wireguard-kmod-8-10-21
root@ubnt:/mnt/data# cd wireguard-kmod-8-10-21/
root@ubnt:/mnt/data/wireguard-kmod-8-10-21# ls
README.building.md  README.md  images  releases  src
root@ubnt:/mnt/data/wireguard-kmod-8-10-21# cd src
root@ubnt:/mnt/data/wireguard-kmod-8-10-21/src# ls
build-wireguard.sh      linux-1.10.0-8.tar.gz  packages  udm-1.10.0-12  udm-1.9.0-10      wireguard
linux-1.10.0-12.tar.gz  linux-1.9.0-10.tar.gz  patches   udm-1.10.0-8   udm-se-1.10.0-12
root@ubnt:/mnt/data/wireguard-kmod-8-10-21/src# cd wireguard
root@ubnt:/mnt/data/wireguard-kmod-8-10-21/src/wireguard# ls
etc  setup_wireguard.sh  usr
root@ubnt:/mnt/data/wireguard-kmod-8-10-21/src/wireguard# ./setup_wireguard.sh
bash: ./setup_wireguard.sh: Permission denied
root@ubnt:/mnt/data/wireguard-kmod-8-10-21/src/wireguard# sudo ./setup_wireguard.sh
sudo: ./setup_wireguard.sh: command not found
root@ubnt:/mnt/data/wireguard-kmod-8-10-21/src/wireguard#
`

**Comment by peacey** [comment]
Hi @jlauzer11, you need to install it in the base OS, not the unifi-os shell. Make sure you're in the base OS and run:

```sh
cd /mnt/data
curl -Ljo wireguard-kmod.tar.Z https://github.com/tusc/wireguard-kmod/releases/download/v8-10-21/wireguard-kmod-08-10-21.tar.Z
tar -C /mnt/data -xvzf wireguard-kmod.tar.Z
cd /mnt/data/wireguard
chmod +x setup_wireguard.sh
./setup_wireguard.sh
```

**Comment by jlauzer11** [comment]
@peacey Thank you so much.  I'm up and running!
