### ISSUE TITLE
Setup tunnel after reboot

### ISSUE THREAD

**Issue by Haasie** [tusc/wireguard-kmod#24]
Hello,

Today i successfully installed wireguard on a udm-pro. Many thanks for that!
One thing i dont know, i followed the guide and installed the bootscript. Copied te setup_wireguard.sh to the right folder.
After i reboot, the tunnel i created does not autostart. Am i doing something wrong?

**Comment by brianfoshee** [comment]
I had to add another `on_boot.d` entry to start the tunnel after reboot:

```
#!/bin/sh
wg-quick up wg0
exit 0
```

Prefix the files with a number so they run in the correct sequence:
`1-setup-wireguard.sh`
`2-start-tunnel.sh`

**Comment by peacey** [comment]
Hi @Haasie,

@brianfoshee is correct. You must add another boot script that to start the tunnel on boot. If you have problems getting that working, please feel free to re-open this issue.
