### ISSUE TITLE
release 8-10-21 does not work on UDMP

### ISSUE THREAD

**Issue by Jollerprutt** [tusc/wireguard-kmod#25]
Hi,
Following the instructions I can't run the setup-wireguard.sh script for release 8-10-21.
I just get permission denied.
7-9-21 works well.
UDM Pro running 1.10.0

**Comment by peacey** [comment]
@Jollerprutt, did you run this first before running the `setup_wireguard.sh` script?

```sh
chmod +x /mnt/data/wireguard/setup_wireguard.sh
```
