### ISSUE TITLE
UDM Pro 1.10.0 - setup_wireguard.sh {modprobe,lsmod,insmod}: not found

### ISSUE THREAD

**Issue by disposedtrolley** [tusc/wireguard-kmod#27]
Hello, thanks for your hard work on this!

I'm trying to install this on my UDM Pro running firmware 1.10.0 and the following kernel:

```command
$ uname -a

Linux ubnt 4.19.152-al-linux-v10.2.0-v1.10.0.3686-a2edd0c #1 SMP Fri Jul 9 04:40:55 UTC 2021 aarch64 GNU/Linux
```

I've extracted the tar to `/mnt/data/wireguard` and have made the `setup_wireguard.sh` script executable. When I try to execute the script however, I get several errors that `modprobe`, `lsmod`, and `insmod` are not found:

```command
$ root@ubnt:/mnt/data/wireguard# ./setup_wireguard.sh

ln: failed to create symbolic link '/bin/bash': File exists
ln: failed to create symbolic link '/usr/bin/htop': File exists
ln: failed to create symbolic link '/usr/sbin/iftop': File exists
ln: failed to create symbolic link '/sbin/resolvconf': File exists
./setup_wireguard.sh: 39: ./setup_wireguard.sh: modprobe: not found
./setup_wireguard.sh: 40: ./setup_wireguard.sh: modprobe: not found
./setup_wireguard.sh: 42: ./setup_wireguard.sh: lsmod: not found
loading wireguard...
./setup_wireguard.sh: 50: ./setup_wireguard.sh: insmod: not found
./setup_wireguard.sh: 52: ./setup_wireguard.sh: insmod: not found
./setup_wireguard.sh: 53: ./setup_wireguard.sh: insmod: not found
```

Are there prerequisite setup steps I've missed? Thanks in advance!

**Comment by peacey** [comment]
Hi @disposedtrolley,

Please make sure you're running this in the base OS and not the unifi-os shell. It seems like you're in the unifi-os shell, so please exit first and install it in the base OS.

**Comment by disposedtrolley** [comment]
Ahh that’s it, thanks for the help @peacey!
