### ISSUE TITLE
Not working any more on the latest official stable UDM Firmware 1.10.4

### ISSUE THREAD

**Issue by marcandre83** [tusc/wireguard-kmod#29]
I have just updated my UDM to the Firmware that was released today. I do now get 'Unsupported Kernel version 4.19.152-al-linux-v10.2.0-v1.10.4.3702-91ba352' when starting setup_wireguard.sh

**Comment by kekonn** [comment]
I am trying out [this release](https://github.com/tusc/wireguard-kmod/releases/tag/v11-05-21) and I get the same error.

uname -a output: `Linux Dream-Machine 4.19.152-al-linux-v10.2.0-v1.10.4.3702-91ba352 #1 SMP Wed Oct 6 14:20:55 UTC 2021 aarch64 GNU/Linux`

**Comment by peacey** [comment]
Hi @kekonn,

I just tried it and it works fine for me on 1.10.4. Please try again and if it doesn't work show the error. Try to install it like this:

```sh
rm -rf /data/wireguard
cd /mnt/data
curl -LJo wireguard-kmod.tar.Z https://github.com/tusc/wireguard-kmod/releases/download/v11-05-21/wireguard-kmod-11-05-21.tar.Z
tar -C /mnt/data -xvzf wireguard-kmod.tar.Z
cd /mnt/data/wireguard
chmod +x setup_wireguard.sh
./setup_wireguard.sh
```

**Comment by kekonn** [comment]
That did it. Could that be because I was in /data instead of /mnt/data before?

**Comment by peacey** [comment]
You shouldn't use /data unless you're using the UDR. For UDM, you should
only use /mnt/data. Yes, I removed that folder to make sure it didn't
install to /data by mistake before.

**Comment by kekonn** [comment]
The instructions seemed to indicate that /mnt/data was only for the UDM Pro. I have an UDM EU and it looks more like the UDR

**Comment by peacey** [comment]
@kekonn I have clarified this in the README now. So hopefully no body else will get confused. Thanks!
