### ISSUE TITLE
Support For UDM Firmware v1.8.x Series

### ISSUE THREAD

**Issue by gaffneyd4** [tusc/wireguard-kmod#3]
Hi Carlos, first of all hats off for your excellent work on this project!
I appreciate all of the great documentation :)

I am running the UDM v1.8.x firmware series (`4.1.37-v1.8.5.2964-30c04be` to be exact).
Do you have any plans for supporting 1.8.x firmware? Or only 1.9.x and up?

It wasn't clear from [this section of the readme](https://github.com/tusc/wireguard-kmod#issues-loading-module) if you were interested in being notified about support for older firmware versions or exclusively newer ones.

I'm trying to evaluate if it is worth the hassle to upgrade my firmware, and based on [recent comments on the v1.9.3 release](https://community.ui.com/releases/UniFi-Dream-Machine-Firmware-1-9-3/c0eef9ce-8bc8-4324-bc5a-dd6ad8520ee0?page=28), I'm leaning towards hanging out in 1.8.5 for the foreseeable future.

Cheers!

**Comment by tusc** [comment]
I just updated the release to include support for 1.8.5. Can you please try and let me know how it works? Thanks.

**Comment by tusc** [comment]
@gaffneyd4 any luck with testing this release?

**Comment by gaffneyd4** [comment]
@tusc thanks for checking back! I will attempt to try this out this weekend!

**Comment by gaffneyd4** [comment]
Super late reply, but I am happy to report that the release works. 😄 Thank you!
