### ISSUE TITLE
Errors when running dmesg

### ISSUE THREAD

**Issue by mbsmetak** [tusc/wireguard-kmod#33]
Hi there,

I have a UDM-Pro running fw 1.10.4 (Network version 6.4.54) that generates errors after running `dmesg`. Attached is the install process and error output.

Thank y'all for doing this really cool project for all of us! 

[udm_1-10-4_wireguardOutput.txt](https://github.com/tusc/wireguard-kmod/files/7493861/udm_1-10-4_wireguardOutput.txt)

**Comment by peacey** [comment]
Hi @mbsmetak,

Your dmesg shows that WireGuard loaded successfully (the last two lines). There are no errors. The rest of the dmesg is not related to the WireGuard module.

**Comment by mbsmetak** [comment]
Thank you and sorry about that!
