### ISSUE TITLE
After installation dmesg doesn't show wireguard

### ISSUE THREAD

**Issue by cloudhaus** [tusc/wireguard-kmod#37]
I'm using UDM-Pro and would like to use wireguard. Thank you for providing this kernel module. 

After running the installation script
```
# ./setup_wireguard.sh
loading wireguard...
# dmesg
```

My dmesg does not show anything relating to wireguard. 

UniFi OS Version
1.10.4

Troubleshooting steps I have taken:
```
# lsmod|egrep ^wireguard
wireguard             131072  0 
```

```
# uname -r
4.19.152-al-linux-v10.2.0-v1.10.4.3702-91ba352
```

Should my wireguard be running at this point?

Thank you!

**Comment by peacey** [comment]
Your lsmod shows that the WireGuard module was loaded successfully. The dmesg is probably just overwritten or you didn't see it. 

In any case, you should be able to use WireGuard now and bring up a tunnel via `wg-quick`.

**Comment by peacey** [comment]
Closing this now as it's answered, but if you have any issues with bringing up the tunnel, please feel free to reopen.
