### ISSUE TITLE
Please add support for firmware v1.10.0-11

### ISSUE THREAD

**Issue by WXbet** [tusc/wireguard-kmod#4]
./setup_wireguard.sh
loading wireguard...
insmod: can't insert '/mnt/data/wireguard/wireguard-4.19.152-al-linux-v10.2.0-v1.10.0-11.3661-7092871.ko': No such file or directory
insmod: can't insert '/mnt/data/wireguard/iptable_raw-4.19.152-al-linux-v10.2.0-v1.10.0-11.3661-7092871.ko': No such file or directory

**Comment by tusc** [comment]
Working on this tonight. Standby.

**Comment by tusc** [comment]
Just published a new release for 1.10.0-11

**Comment by peacey** [comment]
@tusc, is it possible to also update the repo with your new buildroot configs and script changes to compile it with the new 4.19.x kernel? I tried to use the 4.19.x kernel sources at udm-kernel and your build scripts, with the new kernel version tag, and was able to get the the module to compile and load successfully on the UDMP. But when I add a wireguard tunnel the UDMP crashes. With your module, the UDMP doesn't crash. How did you do it?

I would really appreciate if you can tell us how you did it or update the repo with the changes. Thanks!

**Comment by tusc** [comment]
@peacey that's my plan long term. I'm having an issue trying to automate the 4.1.37 & 4.19 build under the same buildroot. I should have the work in progress source committed soon.

**Comment by peacey** [comment]
Thank you very much. I really appreciate your effort in this work. I couldn't get the module to work correctly and I was trying for two days! And there's no way to debug the module because there are no messages after kernel crash so it was very frustrating.

Thanks for putting the time into this!

**Comment by WXbet** [comment]
Thank you @tusc. Kernel modules now loads perfectly:
`[908111.784056] wireguard: WireGuard 1.0.20210424 loaded. See www.wireguard.com for information.`
`[908111.784060] wireguard: Copyright (C) 2015-2019 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.`
