### ISSUE TITLE
Support 1.11.0?

### ISSUE THREAD

**Issue by cwildfoerster** [tusc/wireguard-kmod#40]
Support 1.11.0?

**Comment by peacey** [comment]
Hi @cwildfoerster,

1.11.0 is already supported. Did you get an error or something or you haven't tried it?

**Comment by NimlothPL** [comment]
Is it rly? I don't see libs for 1.11.0 in package

**Comment by bluewalk** [comment]
The wireguard module is now included in the official kernel. You can check `setup_wireguard.sh`, you can see it first checks for the built in and then for a separate module if unavailable.

I can confirm it works, running 1.11.0 with wireguard without additional modules :)

**Comment by cwildfoerster** [comment]
Yes, can confirm too that that update went smooth as butter. @peacey didn't knew the modules are now in the offical kernel, thought we need to get the source code first like with the previous releases.
