### ISSUE TITLE
Unable to bring up a Wireguard Tunnel on UDM-Pro 1.11

### ISSUE THREAD

**Issue by vparres** [tusc/wireguard-kmod#41]
Hello everyone !
My UDM-P has been automagically updated to 1.11 (because auto-upgrade was active, bad idea) and since the update i'm unable to bring my wireguard tunnel up due to an error with `iptables-raw`.

I tried updating the module to lastest version, reboot the UDM but neither solved the issue.

Here are the logs with some useful infos :

```
# wg-quick up wg0
Warning: `/mnt/data/wireguard/etc/wireguard/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.1.42.3/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] ip -4 route add 10.0.1.0/24 dev wg0
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
[#] iptables-restore -n
iptables-restore v1.6.2: iptables-restore: unable to initialize table 'raw'

Error occurred at line: 1
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wg0
```
lsmod :

```
# lsmod
Module                  Size  Used by    Tainted: P
act_mirred             16384  1
cls_u32                24576  1
sch_ingress            16384  1
xt_conntrack           16384  8
nf_nat_tftp            16384  0
nf_conntrack_tftp      16384  1 nf_nat_tftp
nf_nat_pptp            16384  0
nf_conntrack_pptp      16384  1 nf_nat_pptp
nf_nat_h323            20480  0
nf_conntrack_h323      49152  1 nf_nat_h323
nf_nat_proto_gre       16384  1 nf_nat_pptp
nf_conntrack_proto_gre    16384  1 nf_conntrack_pptp
nf_nat_ftp             16384  0
nf_conntrack_ftp       16384  1 nf_nat_ftp
wireguard             126976  0
ip6_udp_tunnel         16384  1 wireguard
udp_tunnel             16384  1 wireguard
nf_log_ipv4            16384  1
nf_log_common          16384  1 nf_log_ipv4
xt_LOG                 16384  1
nf_app                 16384  0
t_miner                49152  1 nf_app
tdts                  438272  1 t_miner
xt_dpi                 16384  0
ifb                    16384  0
ppp_generic            36864  0
slhc                   16384  1 ppp_generic
sch_fq_codel           20480  3
sch_htb                24576  3
ebt_set                16384  3
ebt_arp                16384  2
ebt_ip                 16384  5
ebt_pkttype            16384  4
ebtable_nat            16384  1
ebtables               28672  1 ebtable_nat
lzo                    16384  4
lzo_compress           16384  1 lzo
zram                   24576  1
gpiodev                16384  0
ubnthal              1253376  0
ubnt_common           102400  1 ubnthal
```
And kernel version :

```
# uname -a
Linux ubnt 4.19.152-al-linux-v10.2.0-v1.11.0.3921-f2e3fac #1 SMP Tue Dec 21 08:09:26 UTC 2021 aarch64 GNU/Linux
```

Maybe is there a missing `iptables_raw` kmod ?

Merry Christmas to all of you !

**Comment by peacey** [comment]
Hi @vparres,

1.11 does not have the iptables raw module, however it is not needed (there is a workaround). 

The iptables raw module is only needed when you use 0.0.0.0/0 as an AllowedIPs in your WireGuard config. If you instead replace `AllowedIPs=0.0.0.0/0` with `AllowedIPs=0.0.0.0/1,128.0.0.0/1" then it will work fine.

But why are you using 0.0.0.0/0 on the UDMP WireGuard config? Are you running a WireGuard server on the UDMP or you're using it in client mode? If you're running it as a server, 0.0.0.0/0 doesn't make sense for a server.

**Comment by vparres** [comment]
Hello,

I didn't saw the workaround, i think i was too tired to read every words carefully ...

I'm running Wireguard as a client on the UDM-P, and because i'm currently on Starlink, with a non-French IP Address, i use my tunnel to exit on my server's French IP to overcome some (useless) location restriction.

The workaround worked fine and my tunnel is now up again, thanks for your help !

Once again, Merry Christmas !

**Comment by peacey** [comment]
No worries! Have a great day and a very merry Christmas!

**Comment by pwallner** [comment]
[iptables_raw_1.11.0.zip](https://github.com/tusc/wireguard-kmod/files/7850171/iptables_raw_1.11.0.zip)
here we go with iptables for v1.11.0
