### ISSUE TITLE
Kernel Support for USG-XG-8 3.18.44-ui-qcom

### ISSUE THREAD

**Issue by spamurai2000** [tusc/wireguard-kmod#42]
Downloaded and ran through the installation of wireguard-kmod-11-05-21.tar.Z on my USG-XG-8, reporting 3.18.44-ui-qcom.  setup_wireguard.sh reports back Unsupported Kernel version 3.18.44-ui-qcom.

uname -a reports 3.18.44-ui-qcom #1 SMP Sat Oct 16 01:06:49 CST 2021 aarch64 GNU/Linux

First time to install, so I might have missed something somewhere...

**Comment by peacey** [comment]
Hi @spamurai2000,

The USG is not supported with this project. This project is only for rhe UDM/UDR/UXG. Instead, you can check out [wireguard-vyatta-ubnt](https://github.com/WireGuard/wireguard-vyatta-ubnt/wiki/EdgeOS-and-Unifi-Gateway) project for WireGuard on the USG.

**Comment by spamurai2000** [comment]
Thanks, will do.

**Comment by peacey** [comment]
No worries. Have a Merry Christmas and a happy new year!
