### ISSUE TITLE
UDMPro SE v2.3.11

### ISSUE THREAD

**Issue by bilhackmac** [tusc/wireguard-kmod#47]
Hi.

Thanks for your work, it works perfectly.

Did you test it with an UDMPro SE v2.3.11 ? or there is native kernel module included with this version ?

I'm still on v2.2.12 and I want to be sure tunnels keep working after upgrade as this UDMPro SE is connected with many other UDMPro in differents offices

**Comment by peacey** [comment]
Hi @bilhackmac,

I don't have a UDM SE, so I cannot test this myself unfortunately. So we would appreciate if you could test it for us and see if it works with 2.3.11. I don't know think the SE has a built-in WireGuard module yet, but hopefully the one provided with this package should still work if there weren't any changes to the kernel version. 

So maybe you can test it and show us the error if it doesn't work? Worst case you can always roll back to previous version if it doesn't work.

**Comment by bilhackmac** [comment]
I'd really like to help by updating and testing it but I can't as v2.2.12 it not available to download so no downgrade can be down

**Comment by peacey** [comment]
Hey @bilhackmac, 

Someone using UDM SE 2.3.15 just confirmed to me this module works for them. So you are safe to upgrade!

**Comment by bilhackmac** [comment]
Hi.

Thanks for ping me about that.
And, after updating, I can also confirm that it works.

Thx again for your feedback.
