### ISSUE TITLE
UDM PRO (SE) as Wireguard Client - Routing for LAN Clients

### ISSUE THREAD

**Issue by cstrassmair** [tusc/wireguard-kmod#48]
Hello!
Thanks for this awesome project!

I want to use my home UDM PRO (its an SE) to connect it to my VPS.
Next Step is to route all internet Traffic threw the VPS which is an Ubuntu Wireguard Server.

I can bring up wg0 interface on my UDM PRO SE and can ping the local IP of my VPS.
But my LAN Clients cant. Same when using 0.0.0.0/0 as allowed IPs. Then there is no Internet on Lan Clients.

I think this is as the UDM PRO is a Router yes - but does anyone know how to archive this?

Thanks!
Christoph

**Comment by peacey** [comment]
Hi @cstrassmair,

To route whole Internet through WireGuard is a little tricky to do. You have to setup masquerade rules and choose which clients to force through via ip rules.

There is already a script called [split-vpn](https://github.com/peacey/split-vpn) that can do this all for you. You just tell it which source IPs or networks to force through the VPN, and it sets up the correct rules for you.

**Comment by cstrassmair** [comment]
Hi @peacey - yes meanwhile i found this script and didnt get it working but now i found the problem and it works!

Thanks a lot!

Thumbs up for you guys!

**Comment by gatesry** [comment]
@cstrassmair - What was the problem you solved? Hitting some issues with policy based routing to my VPS.

**Comment by cstrassmair** [comment]
Hi, yes i got the split-vpn script working. There are a lot of Options to set in vpn.conf file. Meanwhile i cant say anything more because i plan to throw my udm pro se out. I want to change to another System.

**Comment by gatesry** [comment]
I'd be willing to buy it off you. You can send me an email if you are interested: hello@gatesryan.com
