### ISSUE TITLE
UDM v1.11.4

### ISSUE THREAD

**Issue by pwallner** [tusc/wireguard-kmod#54]
What do you think, do we need the new kernel or can we use 1.11.0?

Relaease notes from [here](https://community.ui.com/releases/UniFi-OS-Dream-Machines-1-11-4/968091d7-78db-44d7-8b2f-e16a3e8863d3):
`Fix a kernel crash issue.`

I will try today to add only the new version in `versions.txt`

**Comment by DavidB33** [comment]
Hello,
I updated my UDM Pro to v1.11.4 and Wireguard no longer works.
The server is running fine, and I see client requests, but it's not connecting. No LAN access.
I don't know if something needs to be done after updating UDM Pro. Do you have an idea ?

**Comment by pwallner** [comment]
I cannot work, you need a new kernel module for this version... The question is if we could use the same kernel from 1.11.0. I am right now compiling with "old" kernel 1.11.0 and try if its working...

**Comment by peacey** [comment]
Hi @pwallner,

First of all, 1.11 releases including 1.11.4 already have a built-in kernel module and work fine without any update. The script will load the built-in module if it exists.

However, we do build external modules (built-in module is an older version) and you can choose to use that by setting `LOAD_BUILTIN=0` in the `setup_wireguard.sh` script. 

I've actually already built the external module for 1.11.4, but haven't uploaded the release. I'll upload it shortly if you like to use the external module instead. 

@DavidB33,

Something is wrong with your wireguard configuration or firewall. It works fine for me after the update with the built-in module. Please double check your configuration.

**Comment by gatesry** [comment]
Thanks, @peacey for the clarification. I will try the built-in mod on 1.11.4. f

**Comment by pwallner** [comment]
@peacey some misunderstanding. I am the developer from ui-ware and was submitting kernel 1.11.0.

The question was, can we use the "old" kernel or do we have to ask ubiqiti to submit the new one...

Regards
Patrick

Ps: I compiled with old one and it seems wireguard is working

**Comment by peacey** [comment]
Yes @pwallner, as I said, I already compiled the module for 1.11.4 and it's working fine. Hence, there have been no differences to the kernel and we don't have to ask UI for a new one.

**Comment by peacey** [comment]
[New release](https://github.com/tusc/wireguard-kmod/releases/tag/v03-03-22) with external module for 1.11.4 has been uploaded now, for anyone that wishes to use the external module.

**Comment by bluewalk** [comment]
Thanks @peacey, the supposed fix from the changelog from UI actually didn't fix the kernel crashes as in my previous issue. Your's works like a charm!

UI still uses `WireGuard 1.0.20210124` while yours is `WireGuard 1.0.20211208` 👍

**Comment by pwallner** [comment]
@peacey 
Thx. I also think one repository would help all of us. Now there are so many different repos here at github, like yours and also from boostchicken.
Maybe you are willing later to maintain your part in "my" repo? I plan to have several contributors for their parts, otherwise I am not able to keep this up to date. I have a son, and he also consumes a lot from my spare time.
