### ISSUE TITLE
Uninstall instructions

### ISSUE THREAD

**Issue by Ulrar** [tusc/wireguard-kmod#57]
Hi,

Found out Unraid now has a very good integrated wireguard plugin so I started using that instead, and I'd like to remove this from my UDM-Pro. Nothing against this project, served me well for a long time so thanks !

What's the proper way to uninstall this ?
I've removed the setup script from my on_boot.d folder and rebooted, and I now don't have `wg-quick` but I still have `wg`.
I'm not sure what's expected, is it safe to delete the folder under /mnt/data or am I missing steps to remove this cleanly ?

Thanks !

**Comment by tusc** [comment]
@Ulrar , Ubiquiti now ships the wireguard module and the wg binary which is what you are noticing. If you remove the script from on_boot folder then you should be fine.

Nothing is "installed" with wireguard-kmod as the setup script does not survive reboots.

**Comment by Ulrar** [comment]
sorry, forgot to close this.
Thanks !
