### ISSUE TITLE
UDM PRO SE > not surviving reboot

### ISSUE THREAD

**Issue by lowrisk75** [tusc/wireguard-kmod#68]
I can't have WG to survives reboot, probably something I'm doing wrong but 

at boot I have to go to cd /etc/split-vpn/wireguard/mullvad and sh run-vpn.sh 

I did tried this a few time
```
curl -o /etc/systemd/system/run-vpn.service https://raw.githubusercontent.com/peacey/split-vpn/main/examples/boot/run-vpn.service
systemctl daemon-reload && systemctl enable run-vpn
```
but same issue when rebooting

**Comment by turowicz** [comment]
Check this: https://di-marco.net/blog/it/2022-02-02-wireguad_and_split_vpn_on_unifi_dream_machine_pro_se/#surviving-at-reboots

**Comment by lowrisk75** [comment]
> Check this: https://di-marco.net/blog/it/2022-02-02-wireguad_and_split_vpn_on_unifi_dream_machine_pro_se/#surviving-at-reboots

That's great, thank you so much.
