### ISSUE TITLE
1.10.0-13 Fail to load WG

### ISSUE THREAD

**Issue by ivorsmorenburg** [tusc/wireguard-kmod#7]
With latest release I get:

>`# ./setup_wireguard.sh`
>`loading wireguard...`
>`insmod: can't insert '/mnt/data/wireguard/wireguard-4.19.152-al-linux-v10.2.0-v1.10.0-13.3677-0ebe4e`
>`7.ko': No such file or directory`
>`insmod: can't insert '/mnt/data/wireguard/iptable_raw-4.19.152-al-linux-v10.2.0-v1.10.0-13.3677-0ebe`
>`4e7.ko': No such file or directory`

**Comment by peacey** [comment]
Hi @ivorsmorenburg. The latest kernel in 1.10.0-12 (and -13) changed in a way that broke the wireguard module (adding a wireguard link crashed the system), so it wasn't a simple matter of just recompiling it for the new kernel like the previous versions. I have proposed a fix for it in issue #5.

If you want to try out the unofficial fix in the meantime, here are the fixed .ko modules built for -13 that do seem to work: [wireguard-kmod-1.10.0-13.zip](https://github.com/tusc/wireguard-kmod/files/6666130/wireguard-kmod-1.10.0-13.zip).

Just unzip them add the .ko files to your wireguard folder (ignore the patch) and run setup_wireguard.sh again. No guarantees as these are just for testing. Report back if something weird happens.

**Comment by ivorsmorenburg** [comment]
Thanks I'll try on the weekend and report back for any issues found thanks!

**Comment by ivorsmorenburg** [comment]
Works perfectly!
