### ISSUE TITLE
1.12.28 Firmware update has broken WG - UDMP

### ISSUE THREAD

**Issue by Akninja2432** [tusc/wireguard-kmod#70]
Updated to latest os on my udmp this morning and now when i go to initiate the bridge, i get the following:

Welcome to UbiOS

By logging in, accessing, or using the Ubiquiti product, you
acknowledge that you have read and understood the Ubiquiti
License Agreement and agree to be bound by its terms.

root@192.168.2.1's password: 
  ___ ___      .__________.__
 |   |   |____ |__\_  ____/__|
 |   |   /    \|  ||  __) |  |   (c) 2010-2022
 |   |  |   |  \  ||  \   |  |   Ubiquiti Inc.
 |______|___|  /__||__/   |__|
            |_/                  http://www.ui.com

      Welcome to UniFi Dream Machine!

********************************* NOTICE **********************************
* By logging in to, accessing, or using any Ubiquiti product, you are     *
* signifying that you have read our Terms of Service (ToS) and End User   *
* License Agreement (EULA), understand their terms, and agree to be       *
* fully bound to them. The use of CLI (Command Line Interface) can        *
* potentially harm Ubiquiti devices and result in lost access to them and *
* their data. By proceeding, you acknowledge that the use of CLI to       *
* modify device(s) outside of their normal operational scope, or in any   *
* manner inconsistent with the ToS or EULA, will permanently and          *
* irrevocably void any applicable warranty.                               *
***************************************************************************

# wg-quick up wg0
Warning: `/mnt/data/wireguard/etc/wireguard/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
RTNETLINK answers: Operation not supported
Unable to access interface: Protocol not supported
[#] ip link delete dev wg0
Cannot find device "wg0"
# 

Any ideas or thoughts on how to fix this please?

Thanks for this mod!  Been using it for awhile now with no issues until now.

**Comment by peacey** [comment]
FYI, the 1.12.28 release was just pulled by Ubiquiti due to Teleport not working (because of missing wireguard module).

**Comment by Akninja2432** [comment]
Thank you for the update and fixes.  I have rolled back to 1.12.24 as a precaution and all is working great again.  Glad to hear it wasn't something I messed up!

**Comment by bluewalk** [comment]
I see that 1.12.30 is out now, any plans on releasing a kmod for this kernel as wel?

**Comment by peacey** [comment]
Done, @bluewalk!
