### ISSUE TITLE
Missing build for kernel 1.12.33

### ISSUE THREAD

**Issue by bluewalk** [tusc/wireguard-kmod#72]
Hi @tusc,

I see there's no release for kernel 1.12.33.
Can you release your updated version for this kernel too or has this kernel an updated version itself?

Cheers!

**Comment by peacey** [comment]
Hi @bluewalk,

Sorry for the delay. I had compiled it on the 13th of this month but didn't upload it. I have uploaded the [new release now](https://github.com/tusc/wireguard-kmod/releases/tag/v11-13-22). 

Also, the internal module on 1.12.33 is still on an older version 20210124. Custom built is on latest 20220627. 

Regards,
Peacey

**Comment by bluewalk** [comment]
Hi @peacey,

No worries, thanks a bunch! Very nice to have the latest module, now I can upgrade the UDMPro.

Keep up the great work!
