### ISSUE TITLE
Unsupported Kernel version 4.19.152-al-linux-v10.2.0-v1.12.33.4328-5979f88

### ISSUE THREAD

**Issue by wenmangbo** [tusc/wireguard-kmod#74]
./setup_wireguard.sh
ln: failed to create symbolic link '/bin/bash': File exists
ln: failed to create symbolic link '/usr/bin/htop': File exists
ln: failed to create symbolic link '/usr/sbin/iftop': File exists
ln: failed to create symbolic link '/sbin/resolvconf': File exists
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.19.152-al-linux-v10.2.0-v1.12.33.4328-5979f88/modules.dep.bin'
modprobe: FATAL: Module udp_tunnel not found in directory /lib/modules/4.19.152-al-linux-v10.2.0-v1.12.33.4328-5979f88
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.19.152-al-linux-v10.2.0-v1.12.33.4328-5979f88/modules.dep.bin'
modprobe: FATAL: Module ip6_udp_tunnel not found in directory /lib/modules/4.19.152-al-linux-v10.2.0-v1.12.33.4328-5979f88
loading wireguard...
Unsupported Kernel version 4.19.152-al-linux-v10.2.0-v1.12.33.4328-5979f88
root@ubnt:/mnt/data/wireguard# cd  /lib/modules/                           
root@ubnt:/lib/modules# ls
5.10.0-0.deb10.16-rt-arm64
root@ubnt:/lib/modules# cd 5.10.0-0.deb10.16-rt-arm64/
root@ubnt:/lib/modules/5.10.0-0.deb10.16-rt-arm64# ls
kernel         modules.alias.bin  modules.builtin.bin      modules.dep      modules.devname  modules.softdep  modules.symbols.bin
modules.alias  modules.builtin    modules.builtin.modinfo  modules.dep.bin  modules.order    modules.symbols

**Comment by peacey** [comment]
Hi @wenmangbo,

It looks like you're in the unifi-os shell? You're supposed to install and run this in the base OS, not from within the Unifi container. Please exit the container and install it on the base OS.

**Comment by wenmangbo** [comment]
@peacey Thank you very much.
