### ISSUE TITLE
Build for 1.12.38

### ISSUE THREAD

**Issue by bluewalk** [tusc/wireguard-kmod#75]
Good morning @tusc and/or @peacey,

Any chances a build for 1.12.38 is coming? As far as I know this would be the latest 1.x.x version before the move to non podman firmware.
Do you know if they have updated the kernel modules for the 2.x.x firmwares, if not; my hope is still on you guys 😇

Cheers

**Comment by peacey** [comment]
Hi @bluewalk,

Can you show me the output of `uname -a` on 1.12.38? Sorry I'm on 2.x now so I can't downgrade back to 1.12.38 to check the version string. I need it to compile the kernel.

As for 2.x firmware, the built-in module is at version 20210606. So not updated yet. I do hope to compile the new module for 2.x and 3.x releases, but I don't have the kernel sources and need me or someone else to request them from Ubiquiti.

**Comment by bluewalk** [comment]
Hi @peacey, sure thing: `Linux UDM-Pro 4.19.152-al-linux-v10.2.0-v1.12.38.4335-66b5e18 #1 SMP Thu Jan 19 09:25:22 UTC 2023 aarch64 GNU/Linux`

Sad to hear UI still hasn't updated their built-in module yet, let's hope you can get the kernel sources again :)

**Comment by sleepwn** [comment]
Hi @peacey,
  
Just tried the latest release on 1.12.38. Extracted into /data as that seems to be the goto place now (split-vpn chose this location and cant see any /mnt/data). When running setup_wireguard it compains about missing modprobe and insmod, after installing kmod it gives the output below.

No modules folder in /lib, and not able to install with `linux-headers-$(uname -r)` either.

```
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.19.152-al-linux-v10.2.0-v1.12.38.4335-66b5e18/modules.dep.bin'
modprobe: FATAL: Module udp_tunnel not found in directory /lib/modules/4.19.152-al-linux-v10.2.0-v1.12.38.4335-66b5e18
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.19.152-al-linux-v10.2.0-v1.12.38.4335-66b5e18/modules.dep.bin'
modprobe: FATAL: Module ip6_udp_tunnel not found in directory /lib/modules/4.19.152-al-linux-v10.2.0-v1.12.38.4335-66b5e18
```

**Comment by peacey** [comment]
Hi @sleepwn,

I don't think that's right. 1.12.38 still uses /mnt/data and there's no apt program. Are you sure you're in the base OS and not the unifi-os container? It sounds like you're in the container.

**Comment by sleepwn** [comment]
Thats embarrassing, but thanks @peacey. All seems to be working fine then ;)

**Comment by peacey** [comment]
It does get confusing! Glad it's working now @sleepwn.

**Comment by bluewalk** [comment]
> Thanks @bluewalk! Please try the [latest release](https://github.com/tusc/wireguard-kmod/releases/tag/v02-09-23) and tell me how it goes.

Great work, works as expected, as always!

```
[   59.227039] wireguard: WireGuard 1.0.20210124 loaded. See www.wireguard.com for information.
[   59.227042] wireguard: Copyright (C) 2015-2019 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.
[42696.338004] wireguard: WireGuard 1.0.20220627 loaded. See www.wireguard.com for information.
[42696.338007] wireguard: Copyright (C) 2015-2019 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.
```
Big jump from UI's version to yours 👍🏻

**Comment by peacey** [comment]
Hey @bluewalk,

I haven't asked for them yet. But I'm wondering if we should just wait for 3.x because 2.4 and 2.5 are only temporary migration releases until we get to 3.0. I'm not sure if it's worth it getting the sources right now, maybe I'll just wait for 3.0. 

Also, have you tested if you're still experiencing the issue with high traffic crashing the system with Ubiquiti's kernel module on 2.4? Maybe it's not an issue anymore and you can still use their module until 3.x comes out.

**Comment by bluewalk** [comment]
Hi @peacey agreed, it should be a temporary release. I have not yet upgraded, trying to discover the impact of all the customization I made with on_boot.d.

As far as I can tell `/mnt/data` is now `/data`. Will give it a shot over the weekend.
