### ISSUE TITLE
Unsupported Kernel version 3.10.107-UBNT

### ISSUE THREAD

**Issue by tquizzle** [tusc/wireguard-kmod#76]
Unsupported Kernel version 3.10.107-UBNT

Model:       UniFi-Gateway-3
Version:     4.4.57.5578372

Any chance going back to this old stuff?

**Comment by peacey** [comment]
Hi @tquizzle,

This project is only for UnifiOS based systems (UDM series, UDR, UXG). It won't work on USG systems. Please have a look at [wireguard-vyatta-ubnt](https://github.com/WireGuard/wireguard-vyatta-ubnt/wiki/EdgeOS-and-Unifi-Gateway) project for wireguard on USG/UGW/EdgeOS. 

Thanks.
