### ISSUE TITLE
UDMP PRO 2.4.27

### ISSUE THREAD

**Issue by Akninja2432** [tusc/wireguard-kmod#77]
WG not working nor will it install after firmware upgrade.  It wont allow me to roll back either.  Any ideas?

Tia

**Comment by jbagdonas** [comment]
The 2.x OS for UDM/UDMPro uses a persistent storage location of /data instead of /mnt/data, so the directions for the UDM don't apply.

The UDR directions might work for UDMPro on OS 2.x since they are based on that /data location though I haven't tried it yet personally.

Fyi the wireguard kernel module provided with OS 2.4.27 is "1.0.20210606-dirty" according to dmesg.

**Comment by Akninja2432** [comment]
It made it further using the UDR directions.  It wont make the symbiotic links.

**Comment by sdi-brad** [comment]
@jbagdonas @Akninja2432 I got it to work just now. Might be some steps not required but I dug through everything and at least it works for me.

I did a curl -LJo wireguard.kmod.tar.Z https://github.com/tusc/wireguard-kmod/releases/download/v02-09-23.tar.Z

Then extracted to /data with tar -C /data -xvzf wireguard.kmod.tar.Z

Then I edited setup_wireguard.sh and lines I believe 16 & 18 that referenced /mnt/data I changed to /data and saved. 

Then cd /data/wireguard and run chmod +x setup_wireguard.sh

If you run ./setup_wireguard.sh right now you will get symlink errors. Before running ./setup_wireguard.sh make sure to do the following

unlink /bin/bash
unlink /usr/bin/htop
unlink /usr/sbin/iftop
unlink /sbin/resolvconf

Now you can do ./setup_wireguard.sh and off to the races.

**Comment by peacey** [comment]
Hi everyone, 

2.4 and up already comes with both the wireguard module and tools (wg-quick and wg) built-in. You do not need to install this project for UnifiOS 2.4 and up unless you want to use an updated wireguard module (which this project does not currently even have modules for yet anyways).

**Comment by Akninja2432** [comment]
> @jbagdonas @Akninja2432 I got it to work just now. Might be some steps not required but I dug through everything and at least it works for me.
> 
> I did a curl -LJo wireguard.kmod.tar.Z https://github.com/tusc/wireguard-kmod/releases/download/v02-09-23.tar.Z
> 
> Then extracted to /data with tar -C /data -xvzf wireguard.kmod.tar.Z
> 
> Then I edited setup_wireguard.sh and lines I believe 16 & 18 that referenced /mnt/data I changed to /data and saved.
> 
> Then cd /data/wireguard and run chmod +x setup_wireguard.sh
> 
> If you run ./setup_wireguard.sh right now you will get symlink errors. Before running ./setup_wireguard.sh make sure to do the following
> 
> unlink /bin/bash unlink /usr/bin/htop unlink /usr/sbin/iftop unlink /sbin/resolvconf
> 
> Now you can do ./setup_wireguard.sh and off to the races.
> 
> Your wg0.conf sample file is located in /data/wireguard/etc/wireguard/ I'm sure you have your old one backed up like I did, so just create a new wg0.conf in /etc/wireguard

This worked!!! Thanks!
