### ISSUE TITLE
Failed to create symbolic link when trying to run the setup script

### ISSUE THREAD

**Issue by na1lus** [tusc/wireguard-kmod#79]
Hello, 

I recently tried to install wireguard-kmod on my UDM-Pro and ran into this error after trying to run the setup_wireguard.sh
 my output:
ln: failed to create symbolic link '/bin/bash': File exists
ln: failed to create symbolic link '/usr/bin/htop': File exists
ln: failed to create symbolic link '/usr/sbin/iftop': File exists
ln: failed to create symbolic link '/sbin/resolvconf': File exists
ln: failed to create symbolic link '/etc/resolvconf.conf': File exists

I tried erasing everything and redownloading it to the system using the latest update as well but no luck. If you could point me in the right direction I would greatly appreciate it. Thank you for you time and have a great day!

**Comment by peacey** [comment]
Hello @na1lus,

These errors aren't fatal, you can continue even if you see them. 

Also, are you using Unifi OS 2.4 or up? In that case, you don't need to install this script anyways. Wireguard and wg-quick up already comes pre-installed on UnifiOS 2+. So you just need to create your wg0.conf and use wg-quick up as on any system.

**Comment by na1lus** [comment]
Hey peacey,

Thanks for the quick response. Yes, I am using Unifi OS 2.4.27 and I will make my config files and update you if there are any additional errors. Thanks again!
