### ISSUE TITLE
UDM-PRO: resolvconf: command not found

### ISSUE THREAD

**Issue by matt08** [tusc/wireguard-kmod#8]
When I'm trying to connect I get the error:
```
# wg-quick up wg0
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 172.16.0.2/32 dev wg0
[#] ip -6 address add fd01:5ca1:ab1e:8663:2f71:461a:e7d8:53e6/128 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
/usr/bin/wg-quick: line 32: resolvconf: command not found
[#] ip link delete dev wg0
```

New UDM-PRO with the latest firmware.

**Comment by brendon-coop** [comment]
I am experiencing this same issue. For me, it occurs when I attempt to configure a DNS server(s) in the server's config file. If I remove or comment out the DNS line, I am able to successfully bring up the connection.

Is there an alternative method for directing my WireGuard clients to use a particular DNS server? Would it be a good idea to attempt to install resolvconf on the UDM Pro?

**Comment by brendon-coop** [comment]
I experienced this issue when attempting to set a DNS server in the WireGuard server's configuration file under the [Interface] heading. I do not know where I got that idea or if it is even proper practice, but when I configured the DNS properly by setting it in the client configuration file, I was able to bring up my wg0 connection.

I guess what I am saying is to double check your server configuration file for any formatting errors or incompatible settings. If you post your wg0.conf (with any private information redacted), a more trained eye than mine might have a better idea.

**Comment by brendon-coop** [comment]
I experienced this issue when attempting to set a DNS server in the WireGuard server's configuration file under the [Interface] heading. I do not know where I got that idea or if it is even proper practice, but when I configured the DNS properly by setting it in the client configuration file, I was able to bring up my wg0 connection.

I guess what I am saying is to double check your server configuration file for any formatting errors or improper settings. If you post your wg0.conf (with any private information redacted), a more trained eye than mine might have a better idea.

**Comment by peacey** [comment]
@matt08, remove the DNS line from your WireGuard configuration file (wg0.conf). It will start correctly then.

**Comment by matt08** [comment]
@brendon-coop  @peacey
I make couple tests with wireguard config in other env and I think it’s something with DNS parameter in wg0.conf.

My config:
```
    [Interface]
    PrivateKey = ...key...
    Address = 172.16.0.2/32
    Address = fd01:5ca1:ab1e:8663:2f71:461a:e7d8:53e6/128
    DNS = 1.1.1.1
    [Peer]
    PublicKey = ...key...
    AllowedIPs = 0.0.0.0/0
    Endpoint = engage.cloudflareclient.com:2408
```

This config on my test computer:
- No `DNS = x.x.x.x` in config = wireguard connection not working
- `DNS = 1.1.1.1` in config = wireguard connection work great
- `DNS = 192.168.1.x` (local DNS server) in config = wireguard connection not working

This config on UDM-PRO:
- No `DNS = x.x.x.x` in config = wireguard connection established but no internet connection (no ping any IP, no resolve DNS on any device)
- `DNS = 1.1.1.1` in config = wireguard connection error (resolvconf: command not found)
- `DNS = 192.168.1.x` (local DNS server) in config = wireguard connection error (resolvconf: command not found)

At the end I want to use my local DNS (adguard home / pihole) but wireguard doesn't work on UDM-PRO even with 1.1.1.1 or 8.8.8.8 DNS in config. Or without any DNS in config too.

**Comment by peacey** [comment]
@matt08, the DNS option should not affect pinging an IP or establishing a connection. Test the ping on the UDM first, not on devices connected to the UDM. There are extra steps needed to get connected devices to work (such as masquerading). Let's just see if you can get the tunnel up, a handshake working, and pinging through the tunnel working on the UDM.

Do the following to test:

1. Remove DNS option from wg0.conf
2. Run `wg-quick up wg0.conf`
3. Type `wg` and check that you received a handshake. 
4. On the UDM, run `ping -I wg0 1.1.1.1` to check if you are able to ping through the tunnel.

**Comment by matt08** [comment]
> * Type `wg` and check that you received a handshake.
> * On the UDM, run `ping -I wg0 1.1.1.1` to check if you are able to ping through the tunnel.

Received handshake but ping not respond:
```
# wg-quick up wg0
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 172.16.0.2/32 dev wg0
[#] ip -6 address add fd01:5ca1:ab1e:8663:2f71:461a:e7d8:53e6/128 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
[#] iptables-restore -n
# wg
interface: wg0
  public key: RhROV........
  private key: (hidden)
  listening port: 45558
  fwmark: 0xca6c

peer: bmXOC+F1F........
  endpoint: 162.159.192.1:2408
  allowed ips: 0.0.0.0/0
  latest handshake: 8 seconds ago
  transfer: 460 B received, 200.33 KiB sent
# ping -I wg0 1.1.1.1
PING 1.1.1.1 (1.1.1.1): 56 data bytes
^C
--- 1.1.1.1 ping statistics ---
33 packets transmitted, 0 packets received, 100% packet loss
```

**Comment by peacey** [comment]
What is your server configuration like? Did you allow the IP of the client in the server configuration? On the server computer, did you enable masquerading as well as IP forwarding? For example, the following commands run on the server enable masquerading and IP forwarding (replace eth0 with your WAN interface on your server):

```sh
sysctl -w net.ipv4.ip_forward=1
sysctl -w net.ipv6.conf.all.forwarding=1
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
```

**Comment by matt08** [comment]
@peacey I don't make any special configuration.

I'm enable masquerading and IP forwarding (your commands) - noting change.

**Comment by peacey** [comment]
Hi @matt08,

Can you ping the WireGuard server's VPN IP address, not the WAN address, from the wg0 interface? For example, if your server's VPN IP is 172.16.0.1, then run this on the UDMP directly:

```sh
ping -I wg0 172.16.0.1
```

Also, can you try to do a tcpdump on your server (not UDM) when you ping some IP (like 1.1.1.1) through the tunnel on the UDMP? E.g.

On the UDMP run: `ping -I wg0 1.1.1.1`
On the server computer run: `sudo tcpdump -ni any icmp and host 1.1.1.1`

See if you are seeing any packets reaching your server.

**Comment by matt08** [comment]
@peacey thanks for trying to help me.
I can't ping any IP on UDMP after connected without "DNS" parameter in config. On my local computer or smartphone (with the same config) = the same = no ping without "DNS". 

I don't have access to the server computer - this is Cloudflare WRAP VPN (https://1.1.1.1/) with generated config to wireguard (https://github.com/ViRb3/wgcf). And that's work fine everywhere except my UDMP where I get `/usr/bin/wg-quick: line 32: resolvconf: command not found` error.

**Comment by tusc** [comment]
Unfortunately, resolvconf is not included in the base build of the UDM UbiOS. Any DNS reference in the wg0.conf will attempt to update DSN resolution with resolvconf.

**Comment by tusc** [comment]
I just released a new version today with support for resolvconf. Can you please let and let me know if it resolves (no pun) your issue? Thanks.

**Comment by matt08** [comment]
@tusc thanks. Released version help me with resolvconf error. 
Connection established, but I still have no internet connection after that (no ping to any IP). And I don't know why :(

**Comment by peacey** [comment]
Hi @matt08,

As I told you, resolvconf is not the issue. The ping issue is separate than the DNS issue. 

In fact, I tested wgcf and also had a similar problem with no ping working, not only on the UDMP but also on my computer directly. 

I found out there is actually a bug reported in wgcf that does not generate the correct wgcf-profile.conf (the config gets the wrong IP Address for the client). I did get it to work by removing the IPv4 from the Address like in the wgcf-profile.conf file. 

Can you try that to see if it works for you? In your wgcf-profile.conf/wg0.conf, you have two Address defined (one IPv4 and one IPv6). Can you remove the IPv4 line (`Address = 172.16.0.2/32`) but keep the next IPv6 Address line. Then try again and see if pinging works.

**Comment by matt08** [comment]
Hi @peacey 

Thanks once again to trying to help me.

I have another problem with IPv6:
```
# wg-quick up wg0
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 172.16.0.2/32 dev wg0
[#] ip -6 address add fd01:5ca1:ab1e:8cba:e770:8ea:165c:fc63/128 dev wg0
[#] ip link set mtu 1280 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -6 route add ::/0 dev wg0 table 51820
[#] ip -6 rule add not fwmark 51820 table 51820
[#] ip -6 rule add table main suppress_prefixlength 0
[#] ip6tables-restore -n
ip6tables-restore v1.6.1: ip6tables-restore: unable to initialize table 'raw'

Error occurred at line: 1
Try `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.
[#] resolvconf -d wg0 -f
[#] ip -6 rule delete table 51820
[#] ip -6 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wg0
```

So to avoid this error previously in my config ([pasted here](https://github.com/tusc/wireguard-kmod/issues/8#issuecomment-861817898)) I deleted the line `AllowedIPs = ::/0`.

Maybe this is the problem?

**Comment by tusc** [comment]
@matt08,

I just released a new version which now includes support for IPv6. The ip6tables-raw module was not part of previous builds but is now included. This is required for ip6tables-restore. Also, v1.10.0-14 is now supported. Can you please that a try?

**Comment by matt08** [comment]
@tusc,

thanks - that's solve my problem with IPv6. Connection to VPN established (via only IPv6 address as @peacey suggest) but still no ping :(

BTW. On my macOS with same config as UDM-PRO IPv6 connection doesn't work (connection established, no ping). IPv4 work fine :)

**Comment by peacey** [comment]
@matt08, did you ping directly through the wg0 tunnel on the UDM like 

```sh
ping -I wg0 1.1.1.1
```

**Comment by matt08** [comment]
@peacey yes

**Comment by peacey** [comment]
It's been a while so I'm closing this. The original issue with resolvconf was fixed, and the new issue doesn't seem related to the module since it's working fine with literally any other configuration. If you're still trying to do this and want help fixing it, please feel free to open another issue with the problem.

Thanks!
