### ISSUE TITLE
udm-4.19.152 Kernel (from UDM 4.2.27 GPL)

### ISSUE THREAD

**Issue by pwallner** [tusc/wireguard-kmod#80]
Hi @peacey  and @tusc 

just received the new kernel for UDM 
`Linux UDM 4.19.152-ui-alpine-udm #4.19.152 SMP Thu Jan 19 14:13:28 CST 2023 aarch64 GNU/Linux`

[linux-arm64-dream-udm-4.19.152-ui-alpine-udm.tar.gz](http://depositfiles.com/files/nhnwqp7p7).

Cheers
Patrick

**Comment by peacey** [comment]
Thanks again @pwallner. I was able to successfully compile the module with these sources, and I've tested it on UDM 2.5 and the externally compiled module works well (version 1.0.20220627)! You can check out the latest release and try it out yourself (attn: @bluewalk). 

Though one small issue, which isn't new, is that the external module breaks Teleport (there is a workaround I'm using to fix it, but it's not ideal). Do you have the full GPL sources and not just the kernel sources? I want to see if there are any hints or patches to what changes they made to the wireguard module to make it work with Teleport. So I would appreciate if you are able to link the full GPL sources! Thanks!

**Comment by pwallner** [comment]
@peacey Great!!! I will try it today, yesterday I was busy to provide everything on my UDM for nfs and cifs...

Didn't realized that Teleport breaks by the external module, hopefully you find the cause...
Yes I have the full GPL source, here we go [UDM-2.4.27-GPL.tar.gz](http://depositfiles.com/files/z9ihxbwi0)

**Comment by bluewalk** [comment]
Great work ya’ll, I will give it a shot and report back when I get home this weekend 👍🏻

**Comment by pwallner** [comment]
@peacey I think prefix is wrong, should be `4.19.152-ui-alpine-udm`

**Comment by peacey** [comment]
Hey @pwallner,

Thanks for that info, I was not aware udm used a different suffix. Anyhow I compiled it for both now and re-released it. Try out the latest release again. 

Also, thank you for the full GPL sources. Ubiquiti does indeed have some custom [wireguard patches](https://github.com/tusc/wireguard-kmod/tree/main/src/bases/udm-2.4/patches/wireguard-linux-compat) and once I added them to the build, teleport works fine now! So that's fixed now with the custom module. 

@bluewalk, the custom patches explains why the Ubiquiti module was giving you trouble but the one from this project wasn't. But it doesn't seem like you encountered any issues with the 2.4 built-in module, so hopefully they fixed that problem in their patches. Please test the latest release and see if you run into any issues with that same problem.

**Comment by bluewalk** [comment]
> @bluewalk, the custom patches explains why the Ubiquiti module was giving you trouble but the one from this project wasn't. But it doesn't seem like you encountered any issues with the 2.4 built-in module, so hopefully they fixed that problem in their patches. Please test the latest release and see if you run into any issues with that same problem.

It seems their patch is indeed the thing that's causing the following error (no kernel panic yet though) 😀

```[747383.754299] wireguard: vpn0: possible loop detected, dropping skb of size 65216
[747567.960291] wireguard: vpn0: possible loop detected, dropping skb of size 65216
[747569.286610] wireguard: vpn0: possible loop detected, dropping skb of size 65216
[747570.685233] wireguard: vpn0: possible loop detected, dropping skb of size 65216
[747575.765200] wireguard: vpn0: possible loop detected, dropping skb of size 65216
```

as seen here https://github.com/tusc/wireguard-kmod/blob/main/src/bases/udm-2.4/patches/wireguard-linux-compat/041-ubnt-protection-from-routing-loops.patch
No idea why they chose for this check though...

**Comment by mcpat-it** [comment]
@peacey can confirm it works now! Thx!

**Comment by peacey** [comment]
@bluewalk Ya I'm not sure what routing loops this is supposed to fix, but as long as it doesn't give you issues, let's keep it that way. If you ever get kernel panics again because of this, I can always compile the non-patched versions that are not compatible with Teleport for you.

**Comment by peacey** [comment]
Good to hear that @pwallner! Thanks for all the new GPL files again. It would be great if you can keep requesting them once they update to 3.0! That would be really helpful. 

I'll close this issue now since it's completed. Have a great day!

**Comment by mcpat-it** [comment]
@peacey Just to inform you, I just updated my UDM to latest version 2.5.17, now the "-udm" disappeared from uname. So now my UDM acts like your UDM-Pro....
