### ISSUE TITLE
UDM 3.1.x builds

### ISSUE THREAD

**Issue by bluewalk** [tusc/wireguard-kmod#84]
Hi Guys,

It appears that UBNT is still using a super outdated version of wireguard, even on 3.1.14 (which is now an RC).
Any chance your wonderful build gets some love for 3.1.x?

Cheers

**Comment by peacey** [comment]
Hi there @bluewalk,

The current custom module should support the latest 3.1 build, as there doesn't seem to have been any kernel changes. I am using it with no problem. Have you tested it on your end?

Thanks!

**Comment by bluewalk** [comment]
Hi @peacey, I haven't checked it yet, it didn't load with setup_wireguard.sh?

```
[   17.594367] wireguard: WireGuard 1.0.20210606-dirty loaded. See www.wireguard.com for information.
[   17.594370] wireguard: Copyright (C) 2015-2019 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.
```

I had to run `rmmod wireguard` first, now it loads yours:

```
[36686.019504] wireguard: WireGuard 1.0.20220627 loaded. See www.wireguard.com for information.
[36686.019506] wireguard: Copyright (C) 2015-2019 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.
```

**Comment by peacey** [comment]
Yes that's right. The module won't be reloaded if it's already loaded, so you have to rmmod first (you can add the rmmod to the top of the setup script if you need to). And you do need to set `LOAD_BUILTIN=0` too of course.

**Comment by bluewalk** [comment]
Great, will add that to be sure.
UI seems to be autoloading their own nowadays 😐
